ChainCommand:
#    - chain:
#        - "first:command"
#        - "next:command"
#    - chain:
#        - "first:command"
#        - "next:command"
    - chain:
        - "foo:hello"
        - "bar:hi"